### ISSUE TITLE
Deserializing of events from flow_proto fails with transactions with many events

### ISSUE THREAD

**Issue by franklywatson** [janezpodhostnik/flow-py-sdk#66]
A partner reported they are having an issue with this code example: 

```
@app.route('/v2/getInfoByTransactionsId')
async def getInfoByTransactionsIdNew():
    try:
        txId = request.args.get('txId')
        app.logger.info("getInfoByTransactionsIdNew args:txId={}".format(txId))
        transaction = await get_session_client().get_transaction(id=bytes.fromhex(txId))
        transaction_result_response = await get_session_client().get_transaction_result(id=bytes.fromhex(txId))
        result_json = {"id": txId, "authorizers": "[" + "".join([i.hex() for i in transaction.authorizers]) + "]",
                       "events": [json.loads(event.payload.decode("utf-8")) for event in
                                  transaction_result_response.events], "payer": transaction.payer.hex(),
                       "payload": transaction.script.hex(),
                       "status": transaction_status_mapping[transaction_result_response.status]}
        return json.dumps(result_json)
    except Exception:
        traceback.print_exc()
        app.logger.error(traceback.format_exc())
        return traceback.format_exc()
```
They shared that:

> Error occurred in transaction_result_response = await get_session_client().get_transaction_result(id=bytes.fromhex(txId))
> I debug flow sdk. There seem to be some issues here. line 515 in [clinet.py](https://clinet.py/) entities.TransactionResultResponse.from_proto(response, id=id)  There are probably too many events in tx ef6e6dcba87c5f853e0ec940dd382d609ffe11109c28ed239843d71618fa1d71 to from_proto failed.

![photo_6107171108542332275_y](https://github.com/user-attachments/assets/2b1ecbbf-c2f3-4367-b1b4-2ef30e788b42)
![photo_6107171108542332274_y](https://github.com/user-attachments/assets/ca7d1f94-99d7-48f1-a912-508e169d09cb)

**Comment by lealobanov** [comment]
Managed to reproduce the call and 3 of the events are failing to deserialize, please see attached JSON file with a copy of their payloads:
[failed_events.json](https://github.com/user-attachments/files/17538000/failed_events.json)

We have implemented a fix in this PR which adds decoding to nested structures within a payload (seems like the issue was coming from nested fields inside the `Event` payload such as `Entitlements` `authorizations`that were failing to decode). We also tested introducing restrictions on the event payload size or max. number of events per transaction, but those did not appear to cause any issues once the decoding issue was resolved.

PR with fix: https://github.com/janezpodhostnik/flow-py-sdk/pull/67
